POST http://localhost:3001/user HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "name": "root",
    "password": "password"
}

### LOGIN

POST http://localhost:3001/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "password"
}